application: usersource-tasks-test
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /_ah/spi/.*
  script: task_api.application

libraries:
- name: endpoints
  version: 1.0

